enum Types {
    API_GET_MOVIES_PENDING = 'API_GET_PENDING',
    API_GET_TRENDING_MOVIES_PENDING = 'API_GET_TRENDING_PENDING',
    API_GET_MOVIE_PENDING = 'API_GET_MOVIE_PENDING',
    API_GET_MOVIES_SUCCESS = 'API_GET_MOVIES_SUCCESS',
    API_GET_MOVIES_FAILURE = 'API_GET_MOVIES_FAILURE',
    API_GET_TRENDING_MOVIES_SUCCESS = 'API_GET_TRENDING_MOVIES_SUCCESS',
    API_GET_TRENDING_MOVIES_FAILURE = 'API_GET_TRENDING_MOVIES_FAILURE',
    API_GET_MOVIE_SUCCESS = 'API_GET_MOVIE_SUCCESS',
    API_GET_MOVIE_FAILURE = 'API_GET_MOVIE_FAILURE',
}

export default Types;
